### ISSUE TITLE
Option for toggle remembering last search

### ISSUE THREAD

**Issue by ghost** [ggVGc/vim-fuzzysearch#1]
When this plugin has no previous search, it's left in kind of messy output, highlight a single character of nosearch, I can't reproduce this, but if we have option to enable/disable this remembering last search is better.

I found that even close vim and open other file, fuzzysearch still remember old search result from last previous file, that may useful but option would be good.

**Comment by ghost** [comment]
Now I find it more useful :)

**Comment by ggVGc** [comment]
whoops, wrong repo for my previous comment..
I'm not sure I understand what you're requesting here, but good if it works better for you now!
I'm open to adding options for things though, given I understand the wanted behaviour.
