### ISSUE TITLE
E486: Pattern not found: f[^\ ]\{-}d[^\ ]\{-}a[^\ ]\{-}f[^\ ]\{-}d[^\ ]\{-}s?

### ISSUE THREAD

**Issue by tmpm697** [ggVGc/vim-fuzzysearch#4]
When I search for a pattern that not exist, it echoes errors: `E486: Pattern not found: f[^\ ]\{-}d[^\ ]\{-}a[^\ ]\{-}f[^\ ]\{-}d[^\ ]\{-}s`

How to avoid this?

**Comment by ggVGc** [comment]
I assume this is when you are re-executing a previous search, by using up-arrow?
Otherwise I can't reproduce it.
But, echoing this error is standard behaviour of vim I believe? Doing a normal search with `/` also echoes "Pattern not found: ..."

**Comment by tmpm697** [comment]
Exactly this is builtin behavior of vim/neovim when cycle through matched candidates, but seems the string look vaguely. 

Can just echoes "pattern not found" literally?
